#!/bin/bash

jarPath=/home/hadoop/jobs/AtCal/target/atcal-jar-with-dependencies.jar

while getopts "e:pvha:r" arg
do
        case $arg in
             e)
                hadoop jar $jarPath extract $OPTARG
                ;;
             p)
                hadoop jar $jarPath predict
                ;;
             v)
                hadoop jar $jarPath verify
                ;;
             a) hadoop jar $jarPath extract $OPTARG
                hadoop jar $jarPath predict
                hadoop jar $jarPath verify
                ;;
             r) rm -rf aneTmp
                hdfs dfs -rmr /temp/*
                ;;
             h)
                echo "-e    extract, with your setting date like '2017-10-10'"
                echo "-p    predict, following the extract step"
                echo "-v    verify , following the predict step"
                echo "-a    all step , act the 3 steps, with your setting date like '2017-10-10'"
                echo "-r    reset all steps and restart"
                echo "-h    help"
                ;;
             ?)  #当有不认识的选项的时候arg为?
            echo "unkonw argument"
        exit 1
        ;;
        esac
done