#!/bin/bash

jarPath=/home/hadoop/jobs/AtCal/target/atcal-jar-with-dependencies.jar

while getopts "e:pvh" arg
do
        case $arg in
             e)
                hadoop jar $jarPath extract $OPTARG
                ;;
             p)
                hadoop jar $jarPath predict
                ;;
             v)
                hadoop jar $jarPath verify
                ;;
             h)
                echo "-e    extract, with your setting date like '2017-10-10'"
                echo "-p    predict, following the extract step"
                echo "-v    verify , following the predict step"
                echo "-h    help"
                ;;
             ?)  #当有不认识的选项的时候arg为?
            echo "unkonw argument"
        exit 1
        ;;
        esac
done